name: Analysis pipeline

on:
  push:
    branches:
      - main
      - 'ci/**'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.14"

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Compile report
        run: make 

      - name: Export PDF
        uses: actions/upload-artifact@v4
        with:
          name: solutions
          path: solutions.pdf
